#[derive(Clone, Debug)]
pub struct Token{
    pub token_type: TokenType,
    pub line: usize,
    pub position: usize,
}
#[derive(Debug, Clone, PartialEq)]
pub enum TokenType {
    Identifier(String),
    NumberLiteral(f64),
    StringLiteral(String),
    Comment(String),
    Slash,
    Star,
    Plus,
    Minus,
    Semicolon,
    Comma,
    Space,
    Equal,
    OpenParentheses,
    CloseParentheses,
    OpenBrace,
    CloseBrace,
    DoubleEqual,
    Bang,
    BangEqual,
    OpenAngleBracket,
    CloseAngleBracket,
    LessEqual,
    GreaterEqual,
    Dot,
    And,
    Class,
    Else,
    False,
    For,
    Fun,
    If,
    Nil,
    Or,
    Print,
    Return,
    Super,
    This,
    True,
    Var,
    While,
    EOF,
    NewLine,
}